inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('blog/crear_blog/', views.CrearBlog.as_view(), name='crear_blog'),
    path('lista_blogs/', views.ListaDeBlogs.as_view(), name='lista_blogs'),
    path('blog/eliminar_blog/<int:pk>', views.EliminarBlog.as_view(), name='eliminar_blog'),
    path('blog/eliminar_blog/no_puedes/', views.no_puedes_borrar_blog, name= 'no_puedes_borrar_blog'),
    path('blog/editar_blog/<int:pk>', views.EditarBlog.as_view(), name='editar_blog'),
    path('blog/ver_blog/<int:pk>', views.VerBlog.as_view(), name='ver_blog'),
    path('blog/lista_albunes/', views.ListaAlbun.as_view(), name='lista_albun'),
    path('blog/crear_albun/<int:pk>', views.CrearAlbun.as_view(), name='crear_albun'),
    path('blog/lista_albunes/ver_albun/<int:pk>', views.VerAlbun.as_view(), name='ver_albun'),
    path('blog/ver_blog/subir_imagen/', views.SubirImagen.as_view(), name='subir_imagen'),
    path('blog/ver_blog/galeria_imagenes/<int:pk>', views.imagen_galeria, name='imagen_galeria'),
    path('blog/lista_albunes/ver_albun/eliminar_imagen/<int:pk>', views.eliminar_imagen, name='eliminar_imagen'),
    path('blog/lista_albunes/ver_albun/editar_imagen/<int:pk>', views.editar_imagen, name='editar_imagen'),
    path('blog/eliminar_albun/<int:pk>', views.EliminarAlbun.as_view(), name='eliminar_albun'),
    path('blog/editar_albun/<int:pk>', views.editar_albun, name='editar_albun'),
    
]

proyecto_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('mensajeria/', include('mensajeria.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('registrarse/', views.registrarse, name='registrarse'),
    path('perfil/info_perfil/<int:usuario_id>', views.info_perfil, name='info_perfil'),
    path('perfil/info_perfil_autor/<int:usuario_id>', views.info_perfil_autor, name='info_perfil_autor'),
    path('perfil/editar', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/password', views.ModificarPass.as_view(), name='modificar_pass')
    
    
]

inicio/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField



class Blog(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre_blog = models.CharField(max_length=20)
    nombre_autor = models.CharField(max_length=20)
    apellido_autor = models.CharField(max_length=20)
    descripcion = models.TextField(null=True, max_length=100)
    categoria = models.CharField(max_length=2, choices=(
        ('IL', 'Ilustración'),
        ('FT', 'Fotografía'),
        ('AT', 'Arte Tradicional' ),
        ('3D', 'Diseño 3D'),
    ))
    
    def __str__(self):
        return f'Blog: {self.nombre_blog} por {self.nombre_autor}'

class Albun(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Albun: {self.titulo} por {self.autor} - Fecha de creación {self.fecha_creacion}'
    
class Imagen(models.Model):
    albun = models.ForeignKey(Albun, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='galeria/imagenes')
    titulo = models.CharField(max_length=50)
    descripcion = RichTextField(null=True, max_length=800)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Imagen: {self.titulo}'

inicio/views.py
from typing import Any, Dict
from django.db import models
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from django.views.generic.edit import CreateView, UpdateView, DeleteView,FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from inicio.models import *
from inicio.form import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def inicio(request):
    return render(request, 'inicio/inicio.html')


class CrearBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'inicio/crear_blog.html'
    fields = ['nombre_blog', 'nombre_autor', 'apellido_autor', 'categoria', 'descripcion',]
    success_url = reverse_lazy('inicio:lista_blogs')
    
    def form_valid(self, form):
        
        form.instance.autor = self.request.user
        return super().form_valid(form)
    
class ListaDeBlogs(ListView):
    model = Blog
    template_name = "inicio/lista_blogs.html"
    context_object_name = 'blogs'
    
    def get_queryset(self):
        listado_blogs = []
        formulario = BuscarBlogFormulario(self.request.GET)
        if formulario.is_valid():
            nombre_a_buscar = formulario.cleaned_data['nombre']
            listado_blogs = Blog.objects.filter(nombre_blog__icontains=nombre_a_buscar)
        return listado_blogs
    
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['formulario'] = BuscarBlogFormulario
        return contexto
        
    
class EditarBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    template_name = 'inicio/editar_blog.html'
    fields = ['nombre_blog', 'categoria', 'descripcion']
    success_url = reverse_lazy('inicio:lista_blogs')
    
class EliminarBlog(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'inicio/eliminar_blog.html'
    success_url = reverse_lazy('inicio:lista_blogs')
    
    def get_queryset(self):
        queryset=super().get_queryset()
        return queryset.filter(autor=self.request.user)
    def get(self, request,*args, **kwargs):
        blog = self.get_object()
 
        if blog.autor != self.request.user:
            return redirect('inicio:no_puedes_borrar_blog') 
        return super().get(request, *args, **kwargs)
    
        
def no_puedes_borrar_blog(request):
    return render(request, 'inicio/no_puedes_borrar_blog.html')
        
class VerBlog(DetailView):
    model = Blog
    template_name = 'inicio/ver_blog.html'
    context_object_name = 'blog'

class CrearAlbun(LoginRequiredMixin,CreateView):
    model = Albun
    form_class = CrearAlbunFormulario
    template_name = 'inicio/crear_albun.html'
    success_url = reverse_lazy('inicio:lista_albun')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        try:
            blog = Blog.objects.get(pk=pk)
        except Blog.DoesNotExist:
            blog = None
        context['blog'] = blog
        context['form'] = CrearAlbunFormulario(user=self.request.user)
        return context
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
        
       
    def form_valid(self, form):
        blog = self.get_context_data().get('blog')
        if blog:
            form.instance.blog = blog
            form.instance.autor = self.request.user
            
            return super().form_valid(form)
        else:
            return self.form_invalid(form)
        

class ListaAlbun(ListView):
    model = Albun
    template_name = 'inicio/lista_albun.html'
    context_object_name = 'albunes'
    
    def get_queryset(self):
        listado_albun = []
        formulario = BuscarAlbunFormulario(self.request.GET)
        if formulario.is_valid():
            nombre_a_buscar = formulario.cleaned_data['nombre']
            listado_albun = Albun.objects.filter(titulo__icontains=nombre_a_buscar)
        return listado_albun
    
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['formulario'] = BuscarAlbunFormulario
        return contexto
    

class VerAlbun(DetailView):
    model = Albun
    template_name = 'inicio/ver_albun.html'
    context_object_name = 'albun'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        albun = self.get_object()
        imagenes = Imagen.objects.filter(albun=albun)
        context['albun_data'] = [{'albun' : albun, 'imagenes' : imagenes}]
        context['albun_id'] = albun.id
        return context

class EliminarAlbun(LoginRequiredMixin, DeleteView):
    model = Albun
    template_name = 'inicio/eliminar_albun.html'
    success_url = reverse_lazy('inicio:lista_albun')
    
    def get_queryset(self):
        queryset=super().get_queryset()
        return queryset.filter(autor=self.request.user)
    
    
@login_required
def editar_albun(request, pk):
    albun = get_object_or_404(Albun, pk=pk)
    if albun.autor == request.user:
        if request.method == 'POST':
            formulario = EditarAlbunFormulario(request.POST, instance=albun)
            if formulario.is_valid():
                formulario.save()
                return redirect('inicio:ver_albun', pk=albun.pk)
        else:
            formulario = EditarAlbunFormulario(instance=albun)
        return render(request, 'inicio/editar_albun.html', {'formulario': formulario, 'albun': albun})
    else:
        return HttpResponseForbidden('No tienen permiso para editar este álbum')    


class SubirImagen(LoginRequiredMixin, FormView):
    template_name = 'inicio/subir_imagen.html'
    form_class = ImagenFormulario
    success_url = reverse_lazy('inicio:lista_albun')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        nueva_imagen = Imagen(
            imagen = form.cleaned_data['imagen'],
            titulo = form.cleaned_data['titulo'],
            descripcion = form.cleaned_data['descripcion'],
            blog = form.cleaned_data['blog'],
            albun = form.cleaned_data['albun'],
        )
        nueva_imagen.save()
        return super().form_valid(form)
    

def imagen_galeria(request):
    albunes = Albun.objects.all()
    albun_data = []
    for albun in albunes:
        albun_imagenes = Imagen.objects.filter(albun=albun)
        albun_data.append({
            'albun':albun,
            'imagenes': albun_imagenes,
        })
    return render(request, 'inicio/imagenes_galeria.html', {'albun_data':albun_data})

@login_required
def eliminar_imagen(request, pk):
    imagen = get_object_or_404(Imagen, pk=pk)
    if imagen.albun.autor == request.user:
        imagen.delete()
    
    return redirect('inicio:ver_albun', pk=imagen.albun.pk)

@login_required
def editar_imagen(request, pk):
    imagen = get_object_or_404(Imagen, pk=pk)
    if imagen.albun.autor == request.user:
        if request.method == 'POST':
            formulario= EditarImagenFormulario(request.POST, instance=imagen)
            if formulario.is_valid():
                formulario.save()
                return redirect('inicio:ver_albun', pk=imagen.albun.pk)
        else:
            formulario = EditarImagenFormulario(instance=imagen)
        return render(request, 'inicio/editar_imagen.html', {'formulario':formulario, 'imagen':imagen})
    else:
        return HttpResponseForbidden('No tienen permiso para editar esta imagen')

inicio/templates/inicio/crear_albun.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Crear un albun</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Creación de albunes</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">¡Crea tu propio albun!</p>
{% endblock subheading %}

{% block contenido %}
<h1>Crea tu albun</h1>
<table>
    <form method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit' >Crear</button>
    </form>
</table>

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}

{% endblock about %}

{% block contacto %}
{% endblock contacto %}

inicio/templates/inicio/crear_blog.html
{% extends 'base.html' %}

{% block title %}
<title>Crea tu blog</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">¡Crea tu blog!</h1>
{% endblock masterhead %}

{% block subheading %}

<p class="masthead-subheading font-weight-light mb-0">Blog de arte - Ilustración - Fotografía</p>

{% endblock subheading %}

{% block contenido %}
<form action={% url 'inicio:crear_blog' %} method="POST">

    {% csrf_token %}
 
    <table>
        {{form}}
    </table>
    <button>Crear</button>
</form>
{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}


{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

inicio/templates/inicio/editar_albun.html
{% extends 'base.html' %}

{% block title %}
<title>Editar albun</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Editar el albun</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0"></p>
{% endblock subheading %}

{% block contenido %}
<form method="post">
    {% csrf_token %}
    {{ formulario.as_p }}
    <button type="submit">Guardar cambios</button>
    <a href="{% url 'inicio:lista_albun' %}">Cancelar</a>
</form>
{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}
{% endblock contacto %}

inicio/templates/inicio/editar_blog.html
{% extends 'base.html' %}

{% block title %}
<title>Editar</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Editar blog</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Aquí puedes cambiar los datos de tu blog</p>
{% endblock subheading %}

{% block contenido %}

<form action={% url 'inicio:editar_blog' blog.id %} method="POST">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Editar</button>
</form>

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

inicio/templates/inicio/editar_imagen.html
{% extends 'base.html' %}

{% block title %}
<title>Editar imagen</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Editar imagen</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0"></p>
{% endblock subheading %}

{% block contenido %}
<form method='POST' enctype="multipart/form-data" >
    {% csrf_token %}
    {{formulario.as_p}}
    {{formulario.media}}
    <button type='submit'>Guardar cambios</button>
</form>
<a href={% url 'inicio:ver_albun' pk=imagen.albun.pk %}>Cancelar</a>

{% endblock contenido %}
{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}
{% endblock contacto %}

inicio/templates/inicio/eliminar_albun.html
{% extends 'base.html' %}

{% block title %}
<title>Eliminar albun</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Eliminar el albun</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">¿Estás seguro de eliminar el albun?</p>
{% endblock subheading %}

{% block contenido %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


<form method='POST'>
    {% csrf_token %}
    <button type='submit'>Eliminar álbun</button>
    <a href={% url 'inicio:lista_albun' %}>Cancelar</a>
</form>

{% endblock contenido %}
{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}
{% endblock contacto %}

inicio/templates/inicio/eliminar_blog.html
{% extends 'base.html' %}

{% block title %}
<title>Eliminar el blog</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0"></h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0"></p>
{% endblock subheading %}

{% block contenido %}

<form action={% url 'inicio:eliminar_blog' blog.id%} method="POST">
    {% csrf_token %}
    <p>confirmar eliminar el blog {{blog}}</p>
    <button>Confirmar</button>
</form>


{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}
{% comment %} <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Login</h2> {% endcomment %}
{% endblock contacto %}

inicio/templates/inicio/eliminar_imagen.html
{% extends 'base.html' %}

{% block title %}
<title>Congfirmar borrar imagen</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Confirmar eliminación de imagen</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">¿Estás seguro que deseas eliminar esta imagen?</p>
{% endblock subheading %}

{% block contenido %}

<form method='POST'>
    {% csrf_token %}
    <button type= 'submit'> Eliminar</button>
    <a href={% url 'inicio:ver_albun' pk=imagen.albun.pk %}>Cancelar</a>
</form>

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}
{% endblock contacto %}

inicio/templates/inicio/lista_albun.html
{% extends 'base.html' %}

{% block title %}
<title>Albunes</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Listado de albunes</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Blog de arte - Ilustración - Fotografía</p>
{% endblock subheading %}

{% block contenido %}
<h2>Lista de Álbunes</h2>

<form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form>

{% if albunes %}
    {% for albun in albunes %}

    <li>
        {{albun}}
        <button>
            <li><a href={% url 'inicio:ver_albun' albun.pk %}> Ingresar </a></li>
        </button>

        
        <button>
            <li><a href={% url 'inicio:editar_albun' albun.id %}> Editar </a></li>
        </button>
        
        {% if albun.autor == request.user %}
        <button>
            <li><a href={% url 'inicio:eliminar_albun' albun.id %}>Eliminar</a></li>
        </button>
        {% endif %}
        
    
    </li>
    
    {% endfor %}

{% else %}
<p>No se encuentran álbunes</p>

{% endif %}


{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}


{% block about %}
{% endblock about %}

{% block contacto %}
{% endblock contacto %}

inicio/templates/inicio/lista_blogs.html
{% extends 'base.html' %}

{% block title %}
<title>Biblioteca</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Biblioteca de blogs</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Busca el blog que más te interese</p>
{% endblock subheading %}

{% block contenido %}

<form action="" method="get">
    {{formulario}}
    <button>Buscar</button>
</form>
{% if request.user.is_authenticated %}

    <a class='btn btn-primary' href={% url 'inicio:crear_blog' %}>Crea tu blog!</a>

{% endif %}

    <a class='btn btn-primary' href={% url 'inicio:lista_albun' %}>Ver lista de álbunes</a>

{% if blogs %}
{% for blog in blogs %}
<li>
{{blog}}
<button>
    <a class="navbar-brand" href={% url 'inicio:ver_blog' blog.id %}>Ver blog</a>
</button>
<button>
    <a class="navbar-brand" href={% url 'inicio:editar_blog' blog.id %}>Editar blog</a>
</button>
<button>
    <a class="navbar-brand" href={% url 'inicio:eliminar_blog' blog.id %}>Eliminar blog</a>
</button>

</li>

{% endfor %}
{% else %}

<p class="masthead-subheading font-weight-light mb-0">¡Ups! No se han encontrado datos</p>
<button>
    <a class='navbar-brand' href={% url 'inicio:inicio' %}>Volver al menú principal</a>
</button> 
{% endif %}


{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

inicio/templates/inicio/subir_imagen.html
{% extends 'base.html' %}

{% block title %}
<title>Subir imagen</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Cargar una imagen</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">¡Sube las imagenes que tu quieras!</p>
{% endblock subheading %}

{% block contenido %}

{% if request.user.is_authenticated %}
<form action={% url 'inicio:subir_imagen' %} method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
<table>
    {{form}}
    {{form.media}}
</table>
<button>Cargar Imagen</button>
</form> 
{% endif %}
{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}
{% endblock contacto %}

inicio/templates/inicio/ver_albun.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>{{albun.titulo}}</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">{{albun.titulo}}</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Blog de arte - Ilustración - Fotografía</p>
{% endblock subheading %}

{% block contenido %}
<p>  </p>

    <a class='btn btn-primary' href={% url 'usuario:info_perfil_autor' albun.autor.id %}>Información sobre {{albun.autor}}</a>




    <a class='btn btn-primary' href={% url 'inicio:subir_imagen' %}>Cargar Imagen</a>



{% for imagen in object.imagen_set.all %}

    <li>
        <h2>{{imagen.titulo}}</h2>
        <img src={{imagen.imagen.url}} alt={{imagen.titulo}} style="width:800px" enctype='multipart/form-data'>
        <p>{{imagen.descripcion | safe}}</p>
        {% if imagen.albun.autor == request.user%}
            <button>
                <a href={% url 'inicio:eliminar_imagen' pk=imagen.pk %}>Eliminar</a>
            </button>
        {% endif %}
        {% if imagen.albun.autor == request.user %}
        <button>
            <a href={% url 'inicio:editar_imagen' pk=imagen.pk %}>Editar</a>
        </button>
        {% endif %}
    </li>
{% endfor %}

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}
{% endblock contacto %}