inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('blog/crear_blog/', views.CrearBlog.as_view(), name='crear_blog'),
    path('lista_blogs/', views.ListaDeBlogs.as_view(), name='lista_blogs'),
    path('blog/eliminar_blog/<int:pk>', views.EliminarBlog.as_view(), name='eliminar_blog'),
    path('blog/eliminar_blog/no_puedes/', views.no_puedes_borrar_blog, name= 'no_puedes_borrar_blog'),
    path('blog/editar_blog/<int:pk>', views.EditarBlog.as_view(), name='editar_blog'),
    path('blog/ver_blog/<int:pk>', views.VerBlog.as_view(), name='ver_blog'),
    path('blog/lista_albunes/', views.ListaAlbun.as_view(), name='lista_albun'),
    path('blog/crear_albun/<int:pk>', views.CrearAlbun.as_view(), name='crear_albun'),
    path('blog/lista_albunes/ver_albun/<int:pk>', views.VerAlbun.as_view(), name='ver_albun'),
    path('blog/ver_blog/subir_imagen/', views.SubirImagen.as_view(), name='subir_imagen'),
    path('blog/ver_blog/galeria_imagenes/<int:pk>', views.imagen_galeria, name='imagen_galeria'),
    path('blog/lista_albunes/ver_albun/eliminar_imagen/<int:pk>', views.eliminar_imagen, name='eliminar_imagen'),
    path('blog/lista_albunes/ver_albun/editar_imagen/<int:pk>', views.editar_imagen, name='editar_imagen'),
    path('blog/eliminar_albun/<int:pk>', views.EliminarAlbun.as_view(), name='eliminar_albun'),
    path('blog/editar_albun/<int:pk>', views.editar_albun, name='editar_albun'),
    
]

mensajeria/urls.py
from django.urls import path
from .import views

app_name = 'mensajeria'

urlpatterns = [
    path('enviar_mensaje/<int:destinatario_id>/', views.enviar_mensaje, name='enviar_mensaje'),
    path('responder_mensaje/<int:mensaje_id>/', views.responder_mensaje, name='responder_mensaje'),
    path('bandeja_de_entrada/', views.inbox, name='bandeja_de_entrada' )
    
]

proyecto_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('mensajeria/', include('mensajeria.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mensajeria/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Mensajeria(models.Model):
    remitente = models.ForeignKey(User, related_name='mensajes_enviados', on_delete=models.CASCADE)
    destinatario = models.ForeignKey(User, related_name='mensajes_recibidos', on_delete=models.CASCADE)
    contenido = RichTextField()
    fecha_envio = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'De {self.remitente} para {self.destinatario} - {self.fecha_envio}'

mensajeria/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .form import FormularioMensajeria
from .models import *


@login_required
def enviar_mensaje(request, destinatario_id, mensaje_id=None):
    destinatario = User.objects.get(id=destinatario_id)
    # mensaje_original = None
    
    # if mensaje_id:
        # mensaje_original = get_object_or_404(Mensajeria, id=mensaje_id)
    
    if request.method == 'POST':
        formulario = FormularioMensajeria(request.POST)
        if formulario.is_valid():
            mensaje = formulario.save(commit=False)
            mensaje.remitente = request.user
            mensaje.destinatario = destinatario
            
            # if mensaje_original:
            #     mensaje.mensaje_original = mensaje_original
            #     mensaje.destinatario = mensaje_original.destinatario
               
            mensaje.save()
            return redirect('mensajeria:bandeja_de_entrada')
    else:
        formulario = FormularioMensajeria()
        
    return render(request, 'mensajeria/enviar_mensaje.html', {'formulario':formulario, 'destinatario':destinatario}) #'mensaje_original':mensaje_original})

@login_required
def responder_mensaje(request,mensaje_id):
    mensaje_original = get_object_or_404(Mensajeria, id=mensaje_id)
    
    if request.method == 'POST':
        formulario = FormularioMensajeria(request.POST)
        if formulario.is_valid():
            mensaje = formulario.save(commit=False)
            mensaje.remitente = request.user
            mensaje.destinatario = mensaje_original.remitente
            mensaje.mensaje_original = mensaje_original
            mensaje.save()
            return redirect('mensajeria:bandeja_de_entrada')
    else:
        formulario = FormularioMensajeria()
    destinatario_id = mensaje_original.remitente.id
    return render(request, 'mensajeria/responder_mensaje.html', {'formulario':formulario, 'mensaje_original': mensaje_original,'destinatario_id': destinatario_id} )
    
    
def inbox(request):
    user = request.user
    mensajes_recibidos = Mensajeria.objects.filter(destinatario=user).order_by('-fecha_envio')
    return render(request, 'mensajeria/bandeja_de_entrada.html', {'mensajes_recibidos': mensajes_recibidos} )

mensajeria/templates/mensajeria/bandeja_de_entrada.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Enviar mensaje</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Mensajería</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Bandeja de entrada</p>
{% endblock subheading %}

{% block imagen_principal %}
<img class="masthead-avatar mb-5" src={% static 'assets/img/portfolio/correo.png' %} alt="..." />
{% endblock imagen_principal %}

{% block contenido %}
<ul>
    {% for mensaje in mensajes_recibidos %}
        <li>
            <p>De: {{ mensaje.remitente.username }}</p>
            <p>Mensaje: {{ mensaje.contenido|safe}}</p>
            <p>Enviado: {{ mensaje.fecha_envio }}</p>
            <a href={% url 'mensajeria:responder_mensaje' mensaje_id=mensaje.id %} class='btn btn-primary' >Responder</a>
        </li>
    {% endfor %}
</ul>

{% endblock contenido %}

{% block about %}

<li class='btn btn-primary'><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>Volver a Home</a></li>


{% endblock about %}

{% block contacto %}
{% endblock contacto %}

mensajeria/templates/mensajeria/enviar_mensaje.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Enviar mensaje</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Mensajería</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Envía un mensaje a {{destinatario}}</p>
{% endblock subheading %}

{% block imagen_principal %}
<img class="masthead-avatar mb-5" src={% static 'assets/img/portfolio/correo.png' %} alt="..." />
{% endblock imagen_principal %}

{% block contenido %}

<form action={% url 'mensajeria:enviar_mensaje' destinatario_id=destinatario.id %} method='POST'>
    {% csrf_token %}
<table>
    {{formulario}}
    {{formulario.media}}
</table>
<button class='btn btn-primary' >Enviar mensaje</button>
</form> 

{% endblock contenido %}

{% block about %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about %}

{% block contacto %}
{% endblock contacto %}

mensajeria/templates/mensajeria/responder_mensaje.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Enviar mensaje</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Mensajería</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Responder un mensaje a {{mensaje_original.remitente}}</p>
{% endblock subheading %}

{% block imagen_principal %}
<img class="masthead-avatar mb-5" src={% static 'assets/img/portfolio/correo.png' %} alt="..." />
{% endblock imagen_principal %}


{% block contenido %}

<div class="mensaje-original">
    <p>Respuesta a: {{ mensaje_original.remitente.username }}</p>
    <p>Mensaje: {{ mensaje_original.contenido|safe }}</p>
</div>


<form action={% url 'mensajeria:responder_mensaje' mensaje_id=mensaje_original.id %} method='POST'>
    {% csrf_token %}
<table>
    {{formulario}}
    {{formulario.media}}
    <input type="hidden" name="destinatario_id" value="{{ destinatario_id }}">
</table>
<button class='btn btn-primary' >Enviar mensaje</button>
</form> 

{% endblock contenido %}

{% block about %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about %}

{% block contacto %}
{% endblock contacto %}