inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('blog/crear_blog/', views.CrearBlog.as_view(), name='crear_blog'),
    path('lista_blogs/', views.ListaDeBlogs.as_view(), name='lista_blogs'),
    path('blog/eliminar_blog/<int:pk>', views.EliminarBlog.as_view(), name='eliminar_blog'),
    path('blog/eliminar_blog/no_puedes/', views.no_puedes_borrar_blog, name= 'no_puedes_borrar_blog'),
    path('blog/editar_blog/<int:pk>', views.EditarBlog.as_view(), name='editar_blog'),
    path('blog/ver_blog/<int:pk>', views.VerBlog.as_view(), name='ver_blog'),
    path('blog/lista_albunes/', views.ListaAlbun.as_view(), name='lista_albun'),
    path('blog/crear_albun/<int:pk>', views.CrearAlbun.as_view(), name='crear_albun'),
    path('blog/lista_albunes/ver_albun/<int:pk>', views.VerAlbun.as_view(), name='ver_albun'),
    path('blog/ver_blog/subir_imagen/', views.SubirImagen.as_view(), name='subir_imagen'),
    path('blog/ver_blog/galeria_imagenes/<int:pk>', views.imagen_galeria, name='imagen_galeria'),
    path('blog/lista_albunes/ver_albun/eliminar_imagen/<int:pk>', views.eliminar_imagen, name='eliminar_imagen'),
    path('blog/lista_albunes/ver_albun/editar_imagen/<int:pk>', views.editar_imagen, name='editar_imagen'),
    path('blog/eliminar_albun/<int:pk>', views.EliminarAlbun.as_view(), name='eliminar_albun'),
    path('blog/editar_albun/<int:pk>', views.editar_albun, name='editar_albun'),
    
]

mensajeria/urls.py
from django.urls import path
from .import views

app_name = 'mensajeria'

urlpatterns = [
    path('enviar_mensaje/<int:destinatario_id>/', views.enviar_mensaje, name='enviar_mensaje'),
    path('responder_mensaje/<int:mensaje_id>/', views.responder_mensaje, name='responder_mensaje'),
    path('bandeja_de_entrada/', views.inbox, name='bandeja_de_entrada' )
    
]

proyecto_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('mensajeria/', include('mensajeria.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('registrarse/', views.registrarse, name='registrarse'),
    path('perfil/info_perfil/<int:usuario_id>', views.info_perfil, name='info_perfil'),
    path('perfil/info_perfil_autor/<int:usuario_id>', views.info_perfil_autor, name='info_perfil_autor'),
    path('perfil/editar', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/password', views.ModificarPass.as_view(), name='modificar_pass')
    
    
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.

class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    biografia = RichTextField(max_length=1000, null=True, blank=True)

usuario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from usuario.form import MiFormularioDeCreacionDeUsuarios, MiFormularioDeEdicionDeDatosDeUsuario, FormularioCambioPass
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from usuario.models import InfoExtra
from .models import User

# Create your views here.

def login(request):
    if request.method == 'POST':
        
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            
            usuario = formulario.cleaned_data['username']
            contrasenia = formulario.cleaned_data['password']
            
            
            user = authenticate(username=usuario, password=contrasenia)
            
            django_login(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
    
            
            return redirect('inicio:inicio')
    
        else:
            return render(request, 'usuario/login.html', {'formulario': formulario})
    
    formulario = AuthenticationForm()
    return render(request, 'usuario/login.html', {'formulario': formulario})

def registrarse(request):
    if request.method == 'POST':
        formulario = MiFormularioDeCreacionDeUsuarios(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('inicio:inicio')
        else: 
            return render(request, 'usuario/registro.html', {'formulario': formulario})
    formulario = MiFormularioDeCreacionDeUsuarios
    return render(request, 'usuario/registro.html', {'formulario': formulario})


@login_required
def editar_perfil(request):
    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(request.POST, request.FILES, instance= request.user)
        if formulario.is_valid():
            
            avatar = formulario.cleaned_data.get('avatar')
            biografia = formulario.cleaned_data.get('biografia')
            if avatar:
                
                info_extra_user.avatar = avatar
                info_extra_user.save()
            if biografia:
                info_extra_user.biografia = biografia
                info_extra_user.save()
            formulario.save()
            return redirect('usuario:info_perfil')
    else:   
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(initial={'avatar': info_extra_user.avatar, 'biografia': info_extra_user.biografia}, instance=request.user)
        
    return render(request, 'usuario/editar_perfil.html', {'formulario': formulario})

class ModificarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/modificar_pass.html'
    success_url = reverse_lazy('inicio:inicio')
    form_class = FormularioCambioPass
    
def info_perfil(request, usuario_id):
    perfil_usuario = get_object_or_404(User, id=usuario_id)
    return render(request, 'usuario/info_perfil.html', {'perfil_usuario':perfil_usuario})

def info_perfil_autor(request, usuario_id):
    perfil_usuario = get_object_or_404(User, id=usuario_id)
    return render(request, 'usuario/info_perfil_autor.html', {'perfil_usuario':perfil_usuario})

usuario/templates/usuario/editar_perfil.html
{% extends 'base.html' %}

{% block title %}
<title>Editar perfil</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Edición de perfil</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Aquí puedes cambiar los datos de tu perfil</p>
{% endblock subheading %}

{% block contenido %}
<form action={% url 'usuario:editar_perfil' %} method="POST" enctype='multipart/form-data'>
{% csrf_token %}
<table>
    {{formulario}}
    {{formulario.media}}
</table>
<button type='button'><a class= 'navbar-brand' href={% url 'usuario:modificar_pass' %}>Cambiar contraseña</a></button>
<button>Guardar cambios</button>
</form>
<button type='button'><a class= 'navbar-brand' href={% url 'usuario:modificar_pass' %}></a></button>

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

usuario/templates/usuario/info_perfil.html
{% extends 'base.html' %}

{% block title %}
<title>Tu perfil</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Información de perfil</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Aquí puedes ver los datos de tu perfil</p>
{% endblock subheading %}

{% block imagen_principal %}

{% if request.user.infoextra.avatar %}
    <img src={{request.user.infoextra.avatar.url}} alt="" height='400px'>
{% endif %}

{% endblock imagen_principal %}

{% block contenido %}
  
       <p>Nombre de Usuario: {{request.user.username}}</p>
       <p>Nombre: {{request.user.first_name}}</p>
       <p>Apellido: {{request.user.last_name}}</p>
       <p>Email: {{request.user.email}}</p>
       <p>Biografía: {{request.user.infoextra.biografia | safe}} </p>
    

{% if request.user.is_authenticated %}
<button>
   <a href={% url 'usuario:editar_perfil' %}>Editar perfil</a> 
</button>
{% endif %}

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

usuario/templates/usuario/info_perfil_autor.html
{% extends 'base.html' %}

{% block title %}
<title>Tu perfil</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Información de perfil</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Lo que necesites saber sobre {{perfil_usuario.username}}</p>
{% endblock subheading %}

{% block imagen_principal %}

{% if perfil_usuario.infoextra.avatar %}
    <img src={{perfil_usuario.infoextra.avatar.url}} alt="" height='400px'>
{% endif %}

{% endblock imagen_principal %}

{% block contenido %}

    
       <p>Nombre de Usuario: {{perfil_usuario.username}}</p>
       <p>Nombre: {{perfil_usuario.first_name}}</p>
       <p>Apellido: {{perfil_usuario.last_name}}</p>
       <p>Email: {{perfil_usuario.email}}</p>
       <p>Biografía: {{perfil_usuario.infoextra.biografia | safe}} </p>
    
<a class='btn btn-primary' href={% url 'mensajeria:enviar_mensaje' perfil_usuario.id %}>Enviar mensaje a {{perfil_usuario.username}}</a>

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}

{% block title %}
<title>Iniciar sesión</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Iniciar sesión</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Blog de arte - Ilustración - Fotografía</p>
{% endblock subheading %}

{% block contenido %}
<form action={% url 'usuario:login' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Ingresar</button>
</form>
{% endblock contenido %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

usuario/templates/usuario/logout.html
{% extends 'base.html' %}

{% block title %}
<title>¡Adios!</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Has cerrado sesión</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Blog de arte - Ilustración - Fotografía</p>
{% endblock subheading %}

{% block contenido %}

{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

usuario/templates/usuario/modificar_pass.html
{% extends 'base.html' %}

{% block title %}
<title>Cambiar contraseña</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">Cambiar contraseña</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">Recuerda no compartir tu contraseña</p>
{% endblock subheading %}

{% block contenido %}
<form action={% url 'usuario:modificar_pass' %} method="POST">
{% csrf_token %}
<table>
    {{form}}
</table>
<button>Cambiar contraseña</button>
</form>
{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}

usuario/templates/usuario/registro.html
{% extends 'base.html' %}

{% block title %}
<title>Registrarse</title>
{% endblock title %}

{% block masterhead %}
<h1 class="masthead-heading text-uppercase mb-0">¡Registrate aquí!</h1>
{% endblock masterhead %}

{% block subheading %}
<p class="masthead-subheading font-weight-light mb-0">¡Así puedes disfrutar de Natart blogs!</p>
{% endblock subheading %}

{% block contenido %}
<form action={% url 'usuario:registrarse' %} method="POST">
{% csrf_token %}
<table>
    {{formulario}}
</table>
<button>Registrarse</button>
</form>
{% endblock contenido %}

{% block about_inicio %}
<li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href={% url 'inicio:inicio' %}>About</a></li>
{% endblock about_inicio %}

{% block about %}
{% endblock about %}

{% block contacto %}

{% endblock contacto %}